
- name: prepare
  include_tasks: "prepare.yml"

- name: database
  include_tasks: "database.yml"

- name: backup
  include_tasks: "backup.yml"

- name: install
  include_tasks: "install.yml"

- name: customize
  include_tasks: "customize.yml"

- name: finalize
  include_tasks: "finalize.yml"